import { useEffect, useState } from 'react';
import { supabase } from './supabase';

const roles={MEMBER:'Mitglied',SUPPORTER:'Unterstützer',ADMIN:'Admin',HEAD_ADMIN:'Hauptadmin'};
const isAdmin=p=>['ADMIN','HEAD_ADMIN'].includes(p?.role);
function Badge({role}){return <span className="badge">{role==='SUPPORTER'?'★ ':role==='ADMIN'?'★ ':role==='HEAD_ADMIN'?'★★ ':''}{roles[role]||'Mitglied'}</span>}

function Auth({close}){
 const [mode,setMode]=useState('login'),[msg,setMsg]=useState(''),[f,setF]=useState({first_name:'',last_name:'',birth_date:'',nickname:'',email:'',password:''});
 const set=(k,v)=>setF({...f,[k]:v});
 async function submit(e){e.preventDefault();setMsg('');let error;if(mode==='register'){({error}=await supabase.auth.signUp({email:f.email,password:f.password,options:{emailRedirectTo:location.origin,data:f}}));setMsg(error?error.message:'Antrag gespeichert. E-Mail bestätigen, danach muss ein Admin dein Konto freigeben.')}else({error}=await supabase.auth.signInWithPassword({email:f.email,password:f.password}));if(error)setMsg(error.message)}
 return <div className="modal-overlay"><div className="modal"><button className="modal-close" onClick={close}>×</button><p className="eyebrow">ENNSTAL CONNECT</p><h2>{mode==='login'?'Anmelden':'Mitgliedschaft beantragen'}</h2><form onSubmit={submit}>{mode==='register'&&<><input placeholder="Vorname" required value={f.first_name} onChange={e=>set('first_name',e.target.value)}/><input placeholder="Nachname" required value={f.last_name} onChange={e=>set('last_name',e.target.value)}/><input type="date" value={f.birth_date} onChange={e=>set('birth_date',e.target.value)}/><input placeholder="Anzeigename" required value={f.nickname} onChange={e=>set('nickname',e.target.value)}/></>}<input type="email" placeholder="E-Mail" required value={f.email} onChange={e=>set('email',e.target.value)}/><input type="password" minLength="6" placeholder="Passwort" required value={f.password} onChange={e=>set('password',e.target.value)}/><button className="primary-button">{mode==='login'?'Anmelden':'Antrag senden'}</button></form>{msg&&<p>{msg}</p>}<button className="modal-switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Noch kein Mitglied? Antrag stellen':'Schon registriert? Anmelden'}</button></div></div>}

export default function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[tab,setTab]=useState('start'),[auth,setAuth]=useState(false),[posts,setPosts]=useState([]),[members,setMembers]=useState([]),[pending,setPending]=useState([]),[market,setMarket]=useState([]),[text,setText]=useState(''),[edit,setEdit]=useState(false),[notice,setNotice]=useState(''),[chat,setChat]=useState(null),[thread,setThread]=useState([]),[message,setMessage]=useState('');
 const approved=profile&&(profile.status==='APPROVED'||isAdmin(profile)); const name=profile?.nickname||profile?.first_name||'Mein Bereich';
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadProfile();else{setProfile(null);setPosts([]);setMembers([])}},[session]); useEffect(()=>{if(approved)loadAll()},[approved]);
 async function loadProfile(){const {data,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(error)setNotice(error.message);else setProfile(data)}
 async function loadAll(){const [p,m,k]=await Promise.all([supabase.from('posts').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('id,nickname,first_name,last_name,avatar_url,role,is_online,status').eq('status','APPROVED'),supabase.from('marketplace_items').select('*').eq('is_active',true)]);const ids=[...new Set((p.data||[]).map(x=>x.author_id))];let a=[];if(ids.length){const r=await supabase.from('profiles').select('id,nickname,first_name,last_name,avatar_url,role').in('id',ids);a=r.data||[]}const map=Object.fromEntries(a.map(x=>[x.id,x]));setPosts((p.data||[]).map(x=>({...x,author:map[x.author_id]})));setMembers(m.data||[]);setMarket(k.data||[]);if(isAdmin(profile))loadPending()}
 async function loadPending(){const {data}=await supabase.from('profiles').select('*').in('status',['PENDING_ADMIN','PENDING_EMAIL']);setPending(data||[])}
 async function post(e){e.preventDefault();if(!text.trim())return;const {error}=await supabase.from('posts').insert({author_id:profile.id,content:text});if(error)setNotice(error.message);else{setText('');loadAll()}}
 async function save(e){e.preventDefault();const {error}=await supabase.from('profiles').update({nickname:profile.nickname,avatar_url:profile.avatar_url}).eq('id',profile.id);if(error)setNotice(error.message);else{setEdit(false);loadAll();setNotice('Profil gespeichert.') }}
 async function status(id,s){const {error}=await supabase.rpc('set_account_status',{target_user:id,new_status:s,note:''});if(error)setNotice(error.message);else{loadPending();loadAll()}}
 async function openChat(m){setChat(m);setTab('nachrichten');const {data}=await supabase.from('messages').select('*').or(`and(sender_id.eq.${profile.id},receiver_id.eq.${m.id}),and(sender_id.eq.${m.id},receiver_id.eq.${profile.id})`).order('created_at');setThread(data||[])}
 async function send(e){e.preventDefault();if(!message.trim()||!chat)return;const {error}=await supabase.from('messages').insert({sender_id:profile.id,receiver_id:chat.id,content:message});if(error)setNotice(error.message);else{setMessage('');openChat(chat)}}
 async function logout(){await supabase.auth.signOut();setTab('start')}
 return <div className="app"><header className="navbar"><button className="brand" onClick={()=>setTab('start')}><img className="brand-logo" src="/logo.png" alt="Ennstal Connect"/>EnnStal Connect</button><nav>{[['start','Start'],['news','News'],['marktplatz','Marktplatz'],['nachrichten','Nachrichten']].map(([id,l])=><button key={id} onClick={()=>setTab(id)}>{l}</button>)}</nav><div className="nav-auth">{session?<button className="profile-nav-button" onClick={()=>setEdit(true)}>{name}</button>:<><button className="nav-login" onClick={()=>setAuth(true)}>Anmelden</button><button className="nav-register" onClick={()=>setAuth(true)}>Registrieren</button></>}</div></header>
 {!session&&<section className="hero"><div className="hero-content"><p className="eyebrow">DEINE REGION. DEINE COMMUNITY.</p><h1>Willkommen bei<br/>EnnStal Connect</h1><p>Menschen kennenlernen, verbinden, austauschen und gemeinsam die Region erleben.</p><button className="primary-button" onClick={()=>setAuth(true)}>Community entdecken</button></div></section>}
 {session&&!approved&&<main className="page-layout"><div className="empty-state"><h1>Dein Konto wird geprüft</h1><p>{profile?.status==='PENDING_EMAIL'?'Bitte bestätige zuerst deine E-Mail-Adresse.':'Deine Registrierung wartet auf die Freigabe durch einen Admin.'}</p><button className="secondary-button" onClick={logout}>Abmelden</button></div></main>}
 {approved&&<main className="page-layout"><div className="main-content">
 {tab==='start'&&<><section className="hero"><div className="hero-content"><p className="eyebrow">DEINE COMMUNITY</p><h1>Hallo, {name}.</h1><p>Hier findest du deine Community, Neuigkeiten, Nachrichten und lokale Angebote.</p></div></section><div className="welcome-grid"><div className="info-card"><h2>📰 News</h2><p>Teile, was in der Region passiert.</p><button onClick={()=>setTab('news')}>Beiträge ansehen →</button></div><div className="info-card"><h2>💬 Menschen</h2><p>Sieh, wer online ist und starte Gespräche.</p></div><div className="info-card"><h2>🛍️ Marktplatz</h2><p>Entdecke lokale Angebote.</p><button onClick={()=>setTab('marktplatz')}>Marktplatz öffnen →</button></div></div></>}
 {tab==='news'&&<section className="content-section"><div className="section-header"><div><p className="eyebrow">COMMUNITY</p><h1>Aktuelle Beiträge</h1></div></div><form className="editor-card" onSubmit={post}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Was möchtest du mit der Community teilen?"/><div className="editor-actions"><button className="primary-button">Beitrag veröffentlichen</button></div></form><div className="posts">{posts.length===0&&<div className="empty-state">Noch keine Beiträge.</div>}{posts.map(x=>{const a=x.author||{};return <article className="post-card" key={x.id}><div className="post-header">{a.avatar_url?<img className="avatar-image" src={a.avatar_url}/>:<div className="avatar">{(a.nickname||a.first_name||'?')[0]}</div>}<div className="member-name"><h3>{a.nickname||a.first_name||'Mitglied'}</h3><Badge role={a.role}/><p>{new Date(x.created_at).toLocaleString('de-AT')}</p></div></div><p className="post-text">{x.content}</p></article>})}</div></section>}
 {tab==='marktplatz'&&<section className="content-section"><p className="eyebrow">MARKTPLATZ</p><h1>Lokale Angebote</h1><div className="members-grid">{market.length===0?<div className="empty-state">Noch keine Angebote.</div>:market.map(x=><article className="member-card" key={x.id}><small>{x.item_type||'Angebot'}</small><h2>{x.name}</h2><p>{x.description}</p><strong>{x.price?x.price+' Punkte':'Kostenlos'}</strong></article>)}</div></section>}
 {tab==='nachrichten'&&<section className="content-section"><div className="section-header"><div><p className="eyebrow">NACHRICHTEN</p><h1>Mitglieder & Chats</h1></div></div><div className="members-grid">{members.filter(x=>x.id!==profile.id).map(m=><button className="member-card" key={m.id} onClick={()=>openChat(m)}>{m.avatar_url?<img className="member-avatar" src={m.avatar_url}/>:<div className="member-avatar placeholder-avatar">{(m.nickname||m.first_name||'?')[0]}</div>}<h2>{m.nickname||m.first_name} <Badge role={m.role}/></h2><p className="member-location">{m.is_online?'🟢 online':'⚪ offline'}</p>Nachricht schreiben</button>)}</div>{chat&&<div className="editor-card"><h2>Chat mit {chat.nickname||chat.first_name}</h2>{thread.map(x=><p className="post-text" key={x.id}><strong>{x.sender_id===profile.id?'Du':'Mitglied'}:</strong> {x.content}</p>)}<form onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Nachricht schreiben…"/><div className="editor-actions"><button className="primary-button">Senden</button></div></form></div>}</section>}
 </div><aside className="sidebar"><div className="sidebar-card"><p className="sidebar-label">MEIN BEREICH</p><div className="sidebar-profile">{profile.avatar_url?<img src={profile.avatar_url}/>:<div className="sidebar-avatar">{name[0]}</div>}<div><strong>{name}</strong><div className="role-line"><Badge role={profile.role}/></div></div></div><button onClick={()=>setEdit(true)}>👤 Profil bearbeiten</button><button onClick={()=>setTab('nachrichten')}>💬 Nachrichten</button><button onClick={logout} className="logout-button">Abmelden</button></div><div className="sidebar-card"><p className="sidebar-label">ONLINE FREUNDE</p>{members.filter(x=>x.is_online&&x.id!==profile.id).length===0?<p>Gerade niemand online.</p>:members.filter(x=>x.is_online&&x.id!==profile.id).map(m=><button key={m.id} onClick={()=>openChat(m)}>🟢 {m.nickname||m.first_name} <Badge role={m.role}/></button>)}</div>{isAdmin(profile)&&<div className="sidebar-card admin-tools"><p className="sidebar-label">ADMIN TOOLS</p><h2>Freigaben ({pending.length})</h2>{pending.map(u=><div className="admin-member" key={u.id}><strong>{u.nickname||u.first_name||'Neues Mitglied'}</strong><span>{u.status}</span><div><button onClick={()=>status(u.id,'APPROVED')}>✓ Freigeben</button><button onClick={()=>status(u.id,'REJECTED')}>× Ablehnen</button></div></div>)}</div>}</aside></main>}
 {edit&&<div className="modal-overlay"><div className="modal"><button className="modal-close" onClick={()=>setEdit(false)}>×</button><h2>Mein Profil bearbeiten</h2><form onSubmit={save}><label>Anzeigename<input value={profile.nickname||''} onChange={e=>setProfile({...profile,nickname:e.target.value})}/></label><label>Profilbild URL<input value={profile.avatar_url||''} onChange={e=>setProfile({...profile,avatar_url:e.target.value})}/></label><p><Badge role={profile.role}/></p><button className="primary-button">Speichern</button></form></div></div>}
 {auth&&<Auth close={()=>setAuth(false)}/>} {notice&&<div className="loading">{notice}</div>}<footer>© 2026 EnnStal Connect · <button>Impressum</button> · <button>Datenschutz</button> · <button>Community-Regeln</button></footer></div>
}