import { supabase } from "./supabaseClient";
let mounted=false;
const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined)n.textContent=x;return n;};
const sections=[
["Was ist Ennstal Connect?","Ennstal Connect ist eine regionale Community-Plattform für Austausch, Gruppen, Veranstaltungen, Forum, Nachrichten und gemeinsame Aktivitäten. Dein Profil, deine Privatsphäre und deine Sichtbarkeit kannst du selbst steuern."],
["Erste Schritte","Gestalte zuerst dein Profil, lege deine Sichtbarkeit fest und entdecke anschließend Mitglieder, Gruppen, Veranstaltungen und das Forum. Freundschaftsanfragen und Privatnachrichten helfen dir beim direkten Austausch."],
["Online-Zeit & Profildesigns","Ennstal Connect hat kein allgemeines Punktesystem. Bestimmte Profildesigns werden stattdessen abhängig von deiner gesammelten Online-Zeit freigeschaltet. Welche Designs für dich verfügbar sind, siehst du direkt bei der Profilgestaltung."],
["Gruppen & Veranstaltungen","Du kannst Gruppen beitreten, dich austauschen und an Veranstaltungen teilnehmen. Hervorgehobene Gruppen erscheinen zusätzlich als Gruppe der Woche."],
["Forum & Kommentare","Im Forum kannst du eigene Beiträge erstellen und auf andere Beiträge antworten. Wenn jemand auf einen von dir erstellten Forenbeitrag kommentiert, erhältst du automatisch einen Hinweis."],
["Nachrichten & Freundschaftsanfragen","Neue Privatnachrichten und neue Freundschaftsanfragen werden dir automatisch als Hinweis eingeblendet. Über die jeweiligen Bereiche kannst du direkt reagieren."],
["Privatsphäre & Datenschutz","Unter „Meine Daten & Konto“ kannst du deine gespeicherten Daten herunterladen und eine Kontolöschung beantragen. Sichtbarkeitseinstellungen bestimmen, welche Profilangaben andere Mitglieder sehen können."],
["Kontolöschung","Eine Kontolöschung wird zuerst beantragt und nicht sofort durchgeführt. Es gilt eine 14-tägige Rücknahmefrist. Danach wird geprüft, ob gesetzliche Aufbewahrungspflichten, offene Meldungen, aktive Beweissicherungen oder andere zwingende Gründe einer sofortigen Löschung entgegenstehen."],
["Melden & Sicherheit","Problematische Inhalte oder Mitglieder kannst du melden. Meldungen werden von dafür berechtigten Verantwortlichen geprüft. Private Nachrichten sind nicht frei für Admins einsehbar; rechtliche Beweissicherung ist separat geschützt und nur für dokumentierte Rechtsfälle vorgesehen."],
["Support & Ansprechpartner","Für Support kannst du dich an den Betreiber, die angeführten Admins oder Supporter wenden. Die öffentlichen Zuständigkeiten zeigen dir, wer für welchen Bereich zuständig ist."],
["Häufige Fragen","Warum sehe ich bestimmte Profildaten nicht? Weil Mitglieder ihre Sichtbarkeit einschränken können. Warum wird mein Konto nicht sofort gelöscht? Weil zuerst Rücknahmefrist und mögliche rechtliche Pflichten geprüft werden. Wo finde ich meine Daten? Im Bereich „Meine Daten & Konto“." ]
];
function openHelp(){document.querySelector(".ec-help-modal")?.remove();const w=el("div","ec-help-modal"),b=el("div","ec-help-box"),head=el("div","ec-help-head"),x=el("button","ec-help-close","×");x.onclick=()=>w.remove();const title=el("div");title.append(el("span","eyebrow","HILFE & COMMUNITY"),el("h2",null,"So funktioniert Ennstal Connect"));head.append(title,x);const search=el("input","ec-help-search");search.type="search";search.placeholder="Hilfe durchsuchen …";const list=el("div","ec-help-list");sections.forEach(([h,p])=>{const d=document.createElement("details");d.className="ec-help-item";const s=document.createElement("summary");s.textContent=h;d.append(s,el("p",null,p));list.append(d)});search.oninput=()=>{const q=search.value.trim().toLowerCase();list.querySelectorAll(".ec-help-item").forEach(d=>{d.style.display=!q||d.textContent.toLowerCase().includes(q)?"":"none"})};b.append(head,el("p","ec-help-intro","Hier findest du die wichtigsten Funktionen, Datenschutz-Hinweise und Antworten auf typische Fragen."),search,list);w.append(b);document.body.append(w);}
async function mount(){if(mounted)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const target=[...document.querySelectorAll("button,a")].find(n=>/profil|einstellungen|community/i.test(n.textContent||""));if(!target)return;const btn=el("button","ec-help-entry","❓ Hilfe & Community");btn.type="button";btn.onclick=openHelp;target.parentElement?.append(btn);mounted=true;obs.disconnect();}
let timer;const obs=new MutationObserver(()=>{if(mounted)return;clearTimeout(timer);timer=setTimeout(mount,250)});obs.observe(document.documentElement,{childList:true,subtree:true});void mount();