import { supabase } from './supabaseClient';
import { roleIdentity, verifiedState } from './roleIdentity.js';

const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
let profiles=new Map(), friendIds=new Set(), uid=null, busy=false;
const name=p=>String(p?.nickname||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Mitglied').trim();
function icon(src,cls,title){const i=document.createElement('img');i.src=src;i.alt='';i.className=cls;i.title=title;i.setAttribute('aria-label',title);return i;}
function identity(p,{friend=false,compact=false}={}){const r=roleIdentity(p),wrap=document.createElement('span');wrap.className=`ec-pro-identity ec-pro-${r.key}${compact?' is-compact':''}`;wrap.style.setProperty('--ec-id-color',r.color);wrap.append(icon(r.icon,'ec-pro-role-star',r.label));const n=document.createElement('strong');n.className='ec-pro-nickname';n.textContent=name(p);wrap.append(n);if(verifiedState(p))wrap.append(icon('/badge-verified.svg','ec-pro-mini-badge','Verifiziert'));if(friend)wrap.append(icon('/badge-friend.svg','ec-pro-mini-badge','Befreundet'));return wrap;}
function byName(text){const v=String(text||'').replace(/[★♛♥✓]/g,'').trim().toLowerCase();return [...profiles.values()].find(p=>name(p).toLowerCase()===v||v.includes(name(p).toLowerCase()))||null;}
function enhanceMemberCards(){qa('.member-card').forEach(card=>{if(card.dataset.ecIdentity==='1')return;const nick=q('.member-nickname',card);if(!nick)return;const p=byName(nick.textContent);if(!p)return;const friend=friendIds.has(p.id);const old=q('.member-role-line',card);if(old)old.hidden=true;nick.replaceWith(identity(p,{friend}));card.dataset.ecIdentity='1';});}
function enhanceProfile(){qa('.profile-hero,.member-profile-hero,.public-profile-hero').forEach(hero=>{if(hero.dataset.ecIdentity==='1')return;const heading=q('h1',hero);if(!heading)return;const p=byName(heading.textContent);if(!p)return;const row=document.createElement('div');row.className='ec-pro-profile-identity';row.append(identity(p,{friend:friendIds.has(p.id)}));heading.replaceWith(row);qa('.verified-badge,.verification-badge,.friend-indicator',hero).forEach(x=>x.hidden=true);hero.dataset.ecIdentity='1';});}
function enhanceTeam(){qa('.ec-team-person').forEach(card=>{if(card.dataset.ecIdentity==='1')return;const old=q('.ec-team-name',card);if(!old)return;const p=byName(old.textContent);if(!p)return;old.replaceWith(identity(p,{compact:true}));const role=q('.ec-team-role',card);if(role)role.hidden=true;card.dataset.ecIdentity='1';});}
function enhanceAdminCards(){qa('.admin-member-person-button').forEach(btn=>{if(btn.dataset.ecIdentity==='1')return;const old=q('strong',btn);if(!old)return;const p=byName(old.textContent);if(!p)return;old.replaceWith(identity(p,{compact:true}));btn.dataset.ecIdentity='1';});}
function enhanceSmallNames(){qa('.request-card strong,.member-mini strong,.group-moderator,.group-member-list > span').forEach(el=>{if(el.dataset.ecIdentity==='1'||el.closest('.ec-pro-identity'))return;const p=byName(el.textContent);if(!p)return;el.textContent='';el.append(identity(p,{friend:friendIds.has(p.id),compact:true}));el.dataset.ecIdentity='1';});}
function sweep(){enhanceMemberCards();enhanceProfile();enhanceTeam();enhanceAdminCards();enhanceSmallNames();}
async function load(){if(busy)return;busy=true;try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;uid=user.id;const [{data:ps},{data:fs}]=await Promise.all([supabase.from('profiles').select('id,nickname,first_name,last_name,role,account_badge,nickname_color,is_verified,verification_status,account_status').eq('account_status','ACTIVE'),supabase.from('friendships').select('requester_id,receiver_id,status').or(`requester_id.eq.${uid},receiver_id.eq.${uid}`).eq('status','ACCEPTED')]);profiles=new Map((ps||[]).map(p=>[p.id,p]));friendIds=new Set((fs||[]).map(f=>f.requester_id===uid?f.receiver_id:f.requester_id));sweep();}finally{busy=false}}
const observer=new MutationObserver(()=>requestAnimationFrame(sweep));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{load();observer.observe(document.body,{subtree:true,childList:true})},{once:true});else{load();observer.observe(document.body,{subtree:true,childList:true})}
setInterval(()=>{if(!document.hidden)load()},30000);
