import React,{useEffect,useState} from "react";
import {supabase} from "./supabaseClient";
import {loadMemberScores} from "./member-score.js";
import "./kaufpunkte-market-modern.css";
export default function KaufpunkteMarket({user,profile,canManage=false}) {
 const [market,setMarket]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[visible,setVisible]=useState(true);
 const isHead=Boolean(canManage || (profile?.is_primary_head_admin && profile?.account_status==="ACTIVE"));
 const [tab,setTab]=useState("shop");
 const [uploadingSku,setUploadingSku]=useState("");
 const [loading,setLoading]=useState(true);
 const [score,setScore]=useState(null);
 const [authors,setAuthors]=useState({});
 const weekNumber=Math.floor(Date.now()/(7*24*60*60*1000));
 const weeklyItems=(market?.catalog||[]).filter(item=>item.kind==="LAYOUT").sort((a,b)=>a.sku.localeCompare(b.sku));
 const weeklyPick=weeklyItems.length?weeklyItems[weekNumber%weeklyItems.length]:null;
 async function load(){if(!user)return;setLoading(true);try{const [result,scores]=await Promise.all([supabase.rpc("kaufpunkte_my_marketplace"),loadMemberScores([user.id])]);if(scores.has(String(user.id)))setScore(scores.get(String(user.id)));if(!result.error){setMarket(result.data);setError("");return;}const [catalog,account]=await Promise.all([supabase.from("kaufpunkte_catalog").select("sku,title,description,price,kind,active,image_url").eq("active",true).order("price"),supabase.from("profiles").select("points,purchase_points").eq("id",user.id).maybeSingle()]);if(catalog.error)throw result.error;setMarket(current=>({catalog:catalog.data||[],balance:account.data?.purchase_points??profile?.purchase_points??0,normal_points:account.data?.points??profile?.points??0,owned:current?.owned||[],wishlist:current?.wishlist||[],purchase_history:current?.purchase_history||[]}));setError("Die vollständigen Kontodaten konnten nicht geladen werden. Die Angebote werden angezeigt; bitte bei Problemen erneut laden.");}catch(err){setError(err?.message||"Marktplatz konnte nicht geladen werden.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[user?.id]);
 useEffect(()=>{if(!user)return;let live=true;supabase.rpc("kaufpunkte_catalog_authors").then(({data,error})=>{if(live&&!error)setAuthors(Object.fromEntries((data||[]).map(row=>[row.sku,row])));});return()=>{live=false;};},[user?.id,market?.catalog?.length]);
 async function changeAuthor(item){const nick=window.prompt("Neuer Artikelautor (exakter Nickname):",authors[item.sku]?.nickname||"");if(nick===null)return;if(!nick.trim()){setError("Bitte Nickname eingeben.");return;}setBusy(true);const {error}=await supabase.rpc("kaufpunkte_set_author",{p_sku:item.sku,p_nickname:nick.trim()});if(error)setError(error.message);else{const result=await supabase.rpc("kaufpunkte_catalog_authors");if(!result.error)setAuthors(Object.fromEntries((result.data||[]).map(row=>[row.sku,row])));setError("");}setBusy(false);}

 async function buy(sku,title,price){if(!window.confirm(title+" für "+price+" [k] Kaufpunkte kaufen?"))return;setBusy(true);const {error}=await supabase.rpc("kaufpunkte_buy",{p_sku:sku});if(error)setError(error.message);else {await load();window.dispatchEvent(new CustomEvent("ec:points-updated"));}setBusy(false);}
 async function changePrice(sku,current){const raw=window.prompt("Neuer Preis in Kaufpunkten [k]",String(current));if(raw===null)return;const price=Number(raw);if(!Number.isSafeInteger(price)||price<0){setError("Bitte eine gültige ganze Zahl angeben.");return;}setBusy(true);const {error}=await supabase.rpc("kaufpunkte_set_price",{p_sku:sku,p_price:price});if(error)setError(error.message);else await load();setBusy(false);}
 async function uploadImage(sku,file){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setError("Bitte JPG, PNG oder WebP bis 5 MB wählen.");return;}setUploadingSku(sku);setBusy(true);setError("");try{const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const safe=sku.replace(/[^a-zA-Z0-9_-]/g,"-");const path=`marketplace/${safe}-${Date.now()}.${ext}`;const uploaded=await supabase.storage.from("community-images").upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;const url=supabase.storage.from("community-images").getPublicUrl(path).data.publicUrl;const saved=await supabase.rpc("kaufpunkte_set_image",{p_sku:sku,p_image_url:url});if(saved.error)throw saved.error;await load();}catch(e){setError(e.message||"Bild konnte nicht hochgeladen werden.");}finally{setUploadingSku("");setBusy(false);}}
 async function wish(sku){const selected=(market?.wishlist||[]).includes(sku);setBusy(true);const req=selected?supabase.from("kaufpunkte_wishlist").delete().eq("user_id",user.id).eq("sku",sku):supabase.from("kaufpunkte_wishlist").insert({user_id:user.id,sku});const {error}=await req;if(error)setError(error.message);else await load();setBusy(false);}
 if(!user)return <section className="panel"><h2>Marktplatz</h2><p>Bitte melde dich an, um Angebote zu sehen und Kaufpunkte einzulösen.</p></section>;
 return <section className="panel" style={{margin:"16px 0",padding:18}} aria-label="Kaufpunkte-Marktplatz">
 <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}>
 <div className="ec-shop-heading"><span className="eyebrow">NEU · MARKTPLATZ</span><h2 style={{margin:"4px 0"}}>🛍️ Kaufpunkte-Marktplatz</h2><p>Gestalte dein Profil mit Kaufpunkten. Gekaufte Designs bleiben dein Eigentum.</p></div>
 <button className="ec-shop-visibility" type="button" onClick={()=>setVisible(v=>!v)}>{visible?"Marktplatz schließen":"Marktplatz ansehen"}</button>
 </div>
 {loading&&!market&&<p role="status">Marktplatz-Angebote werden geladen …</p>}
 {!loading&&!market&&<button type="button" onClick={()=>void load()}>Erneut laden</button>}
 <div className="ec-market-balances" role="group" aria-label="Deine Punkte und Kaufpunkte"><div className="ec-market-balance"><small>Deine Gesamtpunkte</small><strong>{Number(score??market?.normal_points??profile?.points??0).toLocaleString("de-AT")}</strong><span>Community-Punkte</span></div><div className="ec-market-balance"><small>Verfügbar zum Einkaufen</small><strong>{Number(market?.balance??profile?.purchase_points??0).toLocaleString("de-AT")} [k]</strong><span>Kaufpunkte-Guthaben</span></div></div><p className="ec-market-balance-note">Zwei getrennte Guthaben: Einkäufe reduzieren ausschließlich Kaufpunkte [k], nicht deine Community-Punkte.</p>
 {visible&&<>{!loading&&market&&(market.catalog||[]).length===0&&<p>Derzeit sind noch keine Angebote verfügbar. Neue Artikel erscheinen hier automatisch.</p>}{weeklyPick&&<div style={{padding:14,marginBottom:16,borderRadius:12,background:"linear-gradient(130deg,#17374f,#265c6c)",color:"#fff"}}><strong>✨ Shop der Woche: {weeklyPick.title}</strong><p>{weeklyPick.description} · {weeklyPick.price} [k]</p><small>Jede Woche ein anderes Design im Fokus. Der reguläre Preis bleibt gleich.</small></div>}<div className="ec-shop-tabs" role="group" aria-label="Marktplatzansichten">{[["shop","Shop"],["wishlist","Wunschliste"],["history","Meine Käufe"]].map(([id,title])=><button key={id} className={`ec-shop-tab ${tab===id?"is-active":""}`} type="button" aria-pressed={tab===id} onClick={()=>setTab(id)}>{title}</button>)}</div>{tab==="history"&&<div>{(market?.purchase_history||[]).length?(market.purchase_history||[]).map((p,i)=><p key={i}>{p.sku} · {p.price} [k] · {new Date(p.date).toLocaleDateString("de-AT")}</p>):<p>Noch keine Käufe.</p>}</div>}{market?.highlight_until && new Date(market.highlight_until)>new Date() && <p role="status">✨ Dein Profil ist bis {new Date(market.highlight_until).toLocaleDateString("de-AT")} hervorgehoben. Offizielle Rollen haben immer Vorrang.</p>}<p className="ec-shop-intro">Kaufpunkte erhältst du zusätzlich zu deinen normalen Punkten. Jeder Kauf reduziert nur dein [k]-Guthaben.</p><div className="ec-market-grid" style={{display:tab==="history"?"none":"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,245px),1fr))",gap:12}}>
 {(market?.catalog||[]).filter(item=>tab!=="wishlist"||(market?.wishlist||[]).includes(item.sku)).map(item=>{const owned=!["SUPPORTER","HIGHLIGHT"].includes(item.kind) && (market.owned||[]).includes(item.sku);return <article key={item.sku} className={`ec-market-member-card ec-shop-card ec-shop-${item.kind==="HIGHLIGHT"?"highlight":item.sku.replace(/^theme-/,"")}`} style={{border:"2px solid #e0e8ef",padding:14,borderRadius:16,background:"#fff",boxShadow:"0 5px 18px rgba(25,60,90,.07)"}}>\n {["LAYOUT","SUPPORTER","HIGHLIGHT"].includes(item.kind)?<div className={"ec-market-preview ec-market-preview-"+item.kind.toLowerCase()} aria-label={item.title+" – Mitgliederkarten-Vorschau"} style={{"--preview-color":({"theme-red":"#ff4357","theme-blue":"#1677ff","theme-neon":"#31f7bb","theme-neon-pink":"#ff45ba","theme-alpine":"#508c73","theme-teal":"#009f9a","theme-violet":"#9665da","theme-copper":"#b66e38","theme-aurora":"#62c9f0"}[item.sku]||"#ff7a00"),border:item.kind==="HIGHLIGHT"?"3px solid #ff8b27":item.kind==="SUPPORTER"?"2px solid #e2bd35":"2px solid var(--preview-color)",borderRadius:18,padding:12,marginBottom:12,background:item.kind==="SUPPORTER"?"linear-gradient(145deg,#d5aa09,#927000 55%,#211900)":item.kind==="HIGHLIGHT"?"linear-gradient(145deg,#fff9ea,#ffe8cc)":"linear-gradient(135deg,#f6f9fc,var(--preview-color))",boxShadow:item.kind==="HIGHLIGHT"?"0 0 0 3px rgba(255,137,35,.13),0 12px 28px rgba(255,122,24,.2)":"0 8px 20px rgba(20,40,60,.11)",minHeight:126}}><div style={{fontSize:10,fontWeight:900,color:item.kind==="SUPPORTER"?"#fff4c1":"#39485a",marginBottom:9}}>{item.kind==="HIGHLIGHT"?"✨ HERVORGEHOBEN":item.kind==="SUPPORTER"?"⭐ SUPPORTER":"DESIGN · "+item.title}</div><div className="ec-shop-preview-identity"><div className="ec-shop-preview-author"><small className="ec-shop-author-label">Autor</small><div className="ec-shop-author-line">{authors[item.sku]?.is_primary_head_admin||authors[item.sku]?.role==="HEAD_ADMIN"?<img className="ec-shop-role-star" alt="Hauptadmin-Stern" src="/role-star-red.svg"/>:authors[item.sku]?.role==="ADMIN"?<img className="ec-shop-role-star" alt="Admin-Stern" src="/role-star-blue.svg"/>:authors[item.sku]?.role==="REGIONAL_ADMIN"?<img className="ec-shop-role-star" alt="Regionaladmin-Stern" src="/role-star-green.svg"/>:authors[item.sku]?.role==="SUPPORTER"?<img className="ec-shop-role-star" alt="Supporter-Stern" src="/supporter-star.svg"/>:<img className="ec-shop-role-star" alt="Mitgliederstern" src="/role-star-member.svg"/>}<strong className="ec-shop-preview-nick">{authors[item.sku]?.nickname||"Artikelautor"}</strong></div></div></div></div>:item.image_url?<img src={item.image_url} alt={item.title} loading="lazy" style={{width:"100%",aspectRatio:"16/10",objectFit:"cover",borderRadius:12,marginBottom:10}}/>:<div style={{padding:22,background:"#eef3f7",borderRadius:12,marginBottom:12,textAlign:"center"}}>🛍️ Artikelvorschau</div>}
 {item.image_url&&<img className="ec-shop-product-image" src={item.image_url} alt={`Artikelfoto: ${item.title}`} loading="lazy"/>}
 {!["LAYOUT","SUPPORTER","HIGHLIGHT"].includes(item.kind)&&<div className="ec-shop-preview-identity"><div className="ec-shop-preview-author"><small className="ec-shop-author-label">Autor</small><div className="ec-shop-author-line">{authors[item.sku]?.is_primary_head_admin||authors[item.sku]?.role==="HEAD_ADMIN"?<img className="ec-shop-role-star" alt="Hauptadmin-Stern" src="/role-star-red.svg"/>:authors[item.sku]?.role==="ADMIN"?<img className="ec-shop-role-star" alt="Admin-Stern" src="/role-star-blue.svg"/>:authors[item.sku]?.role==="REGIONAL_ADMIN"?<img className="ec-shop-role-star" alt="Regionaladmin-Stern" src="/role-star-green.svg"/>:authors[item.sku]?.role==="SUPPORTER"?<img className="ec-shop-role-star" alt="Supporter-Stern" src="/supporter-star.svg"/>:<img className="ec-shop-role-star" alt="Mitgliederstern" src="/role-star-member.svg"/>}<strong className="ec-shop-preview-nick">{authors[item.sku]?.nickname||"Artikelautor"}</strong></div></div></div>}
 <strong>{item.kind==="LAYOUT"?"🎨":item.kind==="SUPPORTER"?"⭐":item.kind==="HIGHLIGHT"?"✨":item.kind==="DECORATION"?"🎨":"👀"} {item.title}</strong><p>{item.description}</p><p><strong>{item.price} [k]</strong></p>
 <button className="ec-shop-buy" type="button" disabled={busy||owned||Number(market?.balance??0)<item.price} onClick={()=>buy(item.sku,item.title,item.price)}>{owned?"Bereits erworben":Number(market?.balance??0)<item.price?"Nicht genug [k]":"Jetzt kaufen"}</button>
 <p className="ec-shop-wishlist"><button className="ec-shop-secondary" type="button" disabled={busy} onClick={()=>wish(item.sku)}>{(market?.wishlist||[]).includes(item.sku)?"♥ Von Wunschliste entfernen":"♡ Merken"}</button></p>
 {isHead&&<div style={{display:"grid",gap:8,marginTop:12}}>{profile?.is_primary_head_admin&&<button className="ec-shop-secondary" type="button" disabled={busy} onClick={()=>changeAuthor(item)}>✎ Autor ändern</button>}<button className="ec-shop-secondary ec-shop-edit" type="button" disabled={busy} onClick={()=>changePrice(item.sku,item.price)}>✎ Preis bearbeiten</button><label className="ec-shop-upload">Artikelfoto hochladen (max. 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void uploadImage(item.sku,e.target.files?.[0]);e.target.value="";}}/></label>{uploadingSku===item.sku&&<small>Foto wird hochgeladen …</small>}</div>}</article>})}</div></>}
 {error&&<div role="alert" style={{padding:12,border:"1px solid #e7a19c",borderRadius:12,marginTop:12}}><strong>Marktplatz konnte nicht vollständig geladen werden.</strong><p>{error}</p><button type="button" onClick={()=>void load()}>Erneut versuchen</button></div>}
 </section>;
}