import React,{useEffect,useState} from "react";
import {supabase} from "./supabaseClient";
export default function KaufpunkteMarket({user,profile}) {
 const [market,setMarket]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[visible,setVisible]=useState(true);
 const isHead=Boolean(profile?.is_primary_head_admin && profile?.account_status==="ACTIVE");
 const [tab,setTab]=useState("shop");
 const [uploadingSku,setUploadingSku]=useState("");
 const [loading,setLoading]=useState(true);
 const weekNumber=Math.floor(Date.now()/(7*24*60*60*1000));
 const weeklyItems=(market?.catalog||[]).filter(item=>item.kind==="LAYOUT").sort((a,b)=>a.sku.localeCompare(b.sku));
 const weeklyPick=weeklyItems.length?weeklyItems[weekNumber%weeklyItems.length]:null;
 async function load(){if(!user)return;setLoading(true);try{const {data,error}=await supabase.rpc("kaufpunkte_my_marketplace");if(error)setError(error.message);else{setMarket(data);setError("");}}finally{setLoading(false);}}
 useEffect(()=>{void load();},[user?.id]);
 async function buy(sku,title,price){if(!window.confirm(title+" für "+price+" [k] Kaufpunkte kaufen?"))return;setBusy(true);const {error}=await supabase.rpc("kaufpunkte_buy",{p_sku:sku});if(error)setError(error.message);else await load();setBusy(false);}
 async function changePrice(sku,current){const raw=window.prompt("Neuer Preis in Kaufpunkten [k]",String(current));if(raw===null)return;const price=Number(raw);if(!Number.isSafeInteger(price)||price<0){setError("Bitte eine gültige ganze Zahl angeben.");return;}setBusy(true);const {error}=await supabase.rpc("kaufpunkte_set_price",{p_sku:sku,p_price:price});if(error)setError(error.message);else await load();setBusy(false);}
 async function uploadImage(sku,file){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setError("Bitte JPG, PNG oder WebP bis 5 MB wählen.");return;}setUploadingSku(sku);setBusy(true);setError("");try{const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const safe=sku.replace(/[^a-zA-Z0-9_-]/g,"-");const path=`marketplace/${safe}-${Date.now()}.${ext}`;const uploaded=await supabase.storage.from("community-images").upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;const url=supabase.storage.from("community-images").getPublicUrl(path).data.publicUrl;const saved=await supabase.rpc("kaufpunkte_set_image",{p_sku:sku,p_image_url:url});if(saved.error)throw saved.error;await load();}catch(e){setError(e.message||"Bild konnte nicht hochgeladen werden.");}finally{setUploadingSku("");setBusy(false);}}
 async function wish(sku){const selected=(market?.wishlist||[]).includes(sku);setBusy(true);const req=selected?supabase.from("kaufpunkte_wishlist").delete().eq("user_id",user.id).eq("sku",sku):supabase.from("kaufpunkte_wishlist").insert({user_id:user.id,sku});const {error}=await req;if(error)setError(error.message);else await load();setBusy(false);}
 if(!user)return null;
 return <section className="panel" style={{margin:"16px 0",padding:18}} aria-label="Kaufpunkte-Marktplatz">
 <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}>
 <div><span className="eyebrow">NEU · MARKTPLATZ</span><h2 style={{margin:"4px 0"}}>🛍️ Kaufpunkte-Marktplatz</h2><p>Gestalte dein Profil mit Kaufpunkten. Gekaufte Designs bleiben dein Eigentum.</p></div>
 <button type="button" onClick={()=>setVisible(v=>!v)}>{visible?"Marktplatz schließen":"Marktplatz ansehen"}</button>
 </div>
 {loading&&!market&&<p role="status">Marktplatz-Angebote werden geladen …</p>}
 {!loading&&!market&&<button type="button" onClick={()=>void load()}>Erneut laden</button>}
 <p><strong>{Number(market?.normal_points??profile?.points??0).toLocaleString("de-AT")} Punkte · {Number(market?.balance??profile?.purchase_points??0).toLocaleString("de-AT")} [k]</strong> Kaufpunkte</p>
 {visible&&<>{!loading&&market&&(market.catalog||[]).length===0&&<p>Derzeit sind noch keine Angebote verfügbar. Neue Artikel erscheinen hier automatisch.</p>}{weeklyPick&&<div style={{padding:14,marginBottom:16,borderRadius:12,background:"linear-gradient(130deg,#17374f,#265c6c)",color:"#fff"}}><strong>✨ Shop der Woche: {weeklyPick.title}</strong><p>{weeklyPick.description} · {weeklyPick.price} [k]</p><small>Jede Woche ein anderes Design im Fokus. Der reguläre Preis bleibt gleich.</small></div>}<div style={{display:"flex",gap:8,marginBottom:16,flexWrap:"wrap"}}>{[["shop","Shop"],["wishlist","Wunschliste"],["history","Meine Käufe"]].map(([id,title])=><button key={id} type="button" aria-pressed={tab===id} onClick={()=>setTab(id)}>{title}</button>)}</div>{tab==="history"&&<div>{(market?.purchase_history||[]).length?(market.purchase_history||[]).map((p,i)=><p key={i}>{p.sku} · {p.price} [k] · {new Date(p.date).toLocaleDateString("de-AT")}</p>):<p>Noch keine Käufe.</p>}</div>}{market?.highlight_until && new Date(market.highlight_until)>new Date() && <p role="status">✨ Dein Profil ist bis {new Date(market.highlight_until).toLocaleDateString("de-AT")} hervorgehoben. Offizielle Rollen haben immer Vorrang.</p>}<p>Kaufpunkte erhältst du zusätzlich zu deinen normalen Punkten. Jeder Kauf reduziert nur dein [k]-Guthaben.</p><div className="ec-market-grid" style={{display:tab==="history"?"none":"grid",gridTemplateColumns:"repeat(auto-fit,minmax(225px,1fr))",gap:12}}>
 {(market?.catalog||[]).filter(item=>tab!=="wishlist"||(market?.wishlist||[]).includes(item.sku)).map(item=>{const owned=!["SUPPORTER","HIGHLIGHT"].includes(item.kind) && (market.owned||[]).includes(item.sku);return <article key={item.sku} className="ec-market-member-card" style={{border:"2px solid #e0e8ef",padding:14,borderRadius:16,background:"#fff",boxShadow:"0 5px 18px rgba(25,60,90,.07)"}}>\n {item.image_url?<img src={item.image_url} alt={item.title} loading="lazy" style={{width:"100%",aspectRatio:"16/10",objectFit:"cover",borderRadius:12,marginBottom:10}}/>:<div aria-label="Artikelvorschau" style={{height:110,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#f2f6fa,#e4edf3)",borderRadius:12,marginBottom:10,color:"#365b72",fontWeight:900,fontSize:13}}><span>{item.kind==="LAYOUT"?"🎨 Profil-Design":item.kind==="HIGHLIGHT"?"✨ Hervorhebung":item.kind==="SUPPORTER"?"⭐ Supporter":"🛍️ Marktplatz"}</span></div>}
 {item.kind==="LAYOUT" && <div className={"ec-market-preview "+item.sku} style={{border:"2px solid #6cc7de",borderRadius:14,padding:12,marginBottom:12,background:({"theme-red":"linear-gradient(135deg,#fff0f2,#ff4357)","theme-blue":"linear-gradient(135deg,#edf6ff,#1677ff)","theme-neon":"linear-gradient(135deg,#081b21,#31f7bb)","theme-neon-pink":"linear-gradient(135deg,#23112b,#ff45ba)","theme-alpine":"linear-gradient(135deg,#e9f5ef,#508c73)","theme-teal":"linear-gradient(135deg,#e8faf8,#009f9a)","theme-violet":"linear-gradient(135deg,#f0eaff,#9665da)","theme-copper":"linear-gradient(135deg,#fff1e4,#b66e38)","theme-aurora":"linear-gradient(135deg,#162a4b,#62c9f0)"}[item.sku]||"#356b89"),color:"#fff",minHeight:100}}><div style={{display:"flex",gap:10,alignItems:"center"}}><img src={profile?.avatar_url||"/default-avatar.svg"} alt="" style={{width:42,height:42,borderRadius:"50%"}}/><div><strong>{profile?.nickname||"Dein Profil"}</strong><small style={{display:"block"}}>Mitglied · Profilrahmen</small></div></div></div>}
 {item.kind==="SUPPORTER"&&<div style={{display:"flex",gap:12,alignItems:"center",background:"linear-gradient(145deg,#d5aa09,#927000 55%,#211900)",padding:13,borderRadius:16,border:"2px solid #e2bd35",color:"#fff",marginBottom:12}}><img src={profile?.avatar_url||"/default-avatar.svg"} alt="" style={{width:52,height:52,borderRadius:"50%",border:"2px solid white"}}/><div><strong style={{display:"flex",alignItems:"center",gap:7}}><img src="/supporter-star.svg" alt="Supporter-Stern" style={{width:26,height:26}}/>{profile?.nickname||"Dein Profil"}</strong><small style={{display:"block"}}>Supporter · Mitgliederkarte</small></div></div>}
 <strong>{item.kind==="LAYOUT"?"🎨":item.kind==="SUPPORTER"?"⭐":item.kind==="HIGHLIGHT"?"✨":item.kind==="DECORATION"?"🎨":"👀"} {item.title}</strong><p>{item.description}</p><p><strong>{item.price} [k]</strong></p>
 <button type="button" disabled={busy||owned||Number(market?.balance??0)<item.price} onClick={()=>buy(item.sku,item.title,item.price)}>{owned?"Bereits erworben":Number(market?.balance??0)<item.price?"Nicht genug [k]":"Jetzt kaufen"}</button>
 <p><button type="button" disabled={busy} onClick={()=>wish(item.sku)}>{(market?.wishlist||[]).includes(item.sku)?"♥ Von Wunschliste entfernen":"♡ Merken"}</button></p>
 {isHead&&<div style={{display:"grid",gap:8,marginTop:12}}><button type="button" disabled={busy} onClick={()=>changePrice(item.sku,item.price)}>Preis bearbeiten</button><label style={{fontSize:12,fontWeight:700}}>Artikelfoto hochladen (max. 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void uploadImage(item.sku,e.target.files?.[0]);e.target.value="";}}/></label>{uploadingSku===item.sku&&<small>Foto wird hochgeladen …</small>}</div>}</article>})}</div></>}
 {error&&<p role="alert">{error}</p>}
 </section>;
}