import React,{useEffect,useState} from "react";
import {supabase} from "./supabaseClient";
export default function KaufpunkteMarket({user,profile,canManage=false}) {
 const [market,setMarket]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[visible,setVisible]=useState(true);
 const isHead=Boolean(canManage || (profile?.is_primary_head_admin && profile?.account_status==="ACTIVE"));
 const [tab,setTab]=useState("shop");
 const [uploadingSku,setUploadingSku]=useState("");
 const [loading,setLoading]=useState(true);
 const weekNumber=Math.floor(Date.now()/(7*24*60*60*1000));
 const weeklyItems=(market?.catalog||[]).filter(item=>item.kind==="LAYOUT").sort((a,b)=>a.sku.localeCompare(b.sku));
 const weeklyPick=weeklyItems.length?weeklyItems[weekNumber%weeklyItems.length]:null;
 async function load(){if(!user)return;setLoading(true);try{const {data,error}=await supabase.rpc("kaufpunkte_my_marketplace");if(error)setError(error.message);else{setMarket(data);setError("");}}finally{setLoading(false);}}
 useEffect(()=>{void load();},[user?.id]);
 async function buy(sku,title,price){if(!window.confirm(title+" für "+price+" [k] Kaufpunkte kaufen?"))return;setBusy(true);const {error}=await supabase.rpc("kaufpunkte_buy",{p_sku:sku});if(error)setError(error.message);else await load();setBusy(false);}
 async function changePrice(sku,current){const raw=window.prompt("Neuer Preis in Kaufpunkten [k]",String(current));if(raw===null)return;const price=Number(raw);if(!Number.isSafeInteger(price)||price<0){setError("Bitte eine gültige ganze Zahl angeben.");return;}setBusy(true);const {error}=await supabase.rpc("kaufpunkte_set_price",{p_sku:sku,p_price:price});if(error)setError(error.message);else await load();setBusy(false);}
 async function uploadImage(sku,file){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setError("Bitte JPG, PNG oder WebP bis 5 MB wählen.");return;}setUploadingSku(sku);setBusy(true);setError("");try{const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const safe=sku.replace(/[^a-zA-Z0-9_-]/g,"-");const path=`marketplace/${safe}-${Date.now()}.${ext}`;const uploaded=await supabase.storage.from("community-images").upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;const url=supabase.storage.from("community-images").getPublicUrl(path).data.publicUrl;const saved=await supabase.rpc("kaufpunkte_set_image",{p_sku:sku,p_image_url:url});if(saved.error)throw saved.error;await load();}catch(e){setError(e.message||"Bild konnte nicht hochgeladen werden.");}finally{setUploadingSku("");setBusy(false);}}
 async function wish(sku){const selected=(market?.wishlist||[]).includes(sku);setBusy(true);const req=selected?supabase.from("kaufpunkte_wishlist").delete().eq("user_id",user.id).eq("sku",sku):supabase.from("kaufpunkte_wishlist").insert({user_id:user.id,sku});const {error}=await req;if(error)setError(error.message);else await load();setBusy(false);}
 if(!user)return <section className="panel"><h2>Marktplatz</h2><p>Bitte melde dich an, um Angebote zu sehen und Kaufpunkte einzulösen.</p></section>;
 return <section className="panel" style={{margin:"16px 0",padding:18}} aria-label="Kaufpunkte-Marktplatz">
 <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}>
 <div><span className="eyebrow">NEU · MARKTPLATZ</span><h2 style={{margin:"4px 0"}}>🛍️ Kaufpunkte-Marktplatz</h2><p>Gestalte dein Profil mit Kaufpunkten. Gekaufte Designs bleiben dein Eigentum.</p></div>
 <button type="button" onClick={()=>setVisible(v=>!v)}>{visible?"Marktplatz schließen":"Marktplatz ansehen"}</button>
 </div>
 {loading&&!market&&<p role="status">Marktplatz-Angebote werden geladen …</p>}
 {!loading&&!market&&<button type="button" onClick={()=>void load()}>Erneut laden</button>}
 <p><strong>{Number(market?.normal_points??profile?.points??0).toLocaleString("de-AT")} Punkte · {Number(market?.balance??profile?.purchase_points??0).toLocaleString("de-AT")} [k]</strong> Kaufpunkte</p>
 {visible&&<>{!loading&&market&&(market.catalog||[]).length===0&&<p>Derzeit sind noch keine Angebote verfügbar. Neue Artikel erscheinen hier automatisch.</p>}{weeklyPick&&<div style={{padding:14,marginBottom:16,borderRadius:12,background:"linear-gradient(130deg,#17374f,#265c6c)",color:"#fff"}}><strong>✨ Shop der Woche: {weeklyPick.title}</strong><p>{weeklyPick.description} · {weeklyPick.price} [k]</p><small>Jede Woche ein anderes Design im Fokus. Der reguläre Preis bleibt gleich.</small></div>}<div style={{display:"flex",gap:8,marginBottom:16,flexWrap:"wrap"}}>{[["shop","Shop"],["wishlist","Wunschliste"],["history","Meine Käufe"]].map(([id,title])=><button key={id} type="button" aria-pressed={tab===id} onClick={()=>setTab(id)}>{title}</button>)}</div>{tab==="history"&&<div>{(market?.purchase_history||[]).length?(market.purchase_history||[]).map((p,i)=><p key={i}>{p.sku} · {p.price} [k] · {new Date(p.date).toLocaleDateString("de-AT")}</p>):<p>Noch keine Käufe.</p>}</div>}{market?.highlight_until && new Date(market.highlight_until)>new Date() && <p role="status">✨ Dein Profil ist bis {new Date(market.highlight_until).toLocaleDateString("de-AT")} hervorgehoben. Offizielle Rollen haben immer Vorrang.</p>}<p>Kaufpunkte erhältst du zusätzlich zu deinen normalen Punkten. Jeder Kauf reduziert nur dein [k]-Guthaben.</p><div className="ec-market-grid" style={{display:tab==="history"?"none":"grid",gridTemplateColumns:"repeat(auto-fit,minmax(225px,1fr))",gap:12}}>
 {(market?.catalog||[]).filter(item=>tab!=="wishlist"||(market?.wishlist||[]).includes(item.sku)).map(item=>{const owned=!["SUPPORTER","HIGHLIGHT"].includes(item.kind) && (market.owned||[]).includes(item.sku);return <article key={item.sku} className="ec-market-member-card" style={{border:"2px solid #e0e8ef",padding:14,borderRadius:16,background:"#fff",boxShadow:"0 5px 18px rgba(25,60,90,.07)"}}>\n {["LAYOUT","SUPPORTER","HIGHLIGHT"].includes(item.kind)?<div className={"ec-market-preview ec-market-preview-"+item.kind.toLowerCase()} aria-label={item.title+" – Mitgliederkarten-Vorschau"} style={{"--preview-color":({"theme-red":"#ff4357","theme-blue":"#1677ff","theme-neon":"#31f7bb","theme-neon-pink":"#ff45ba","theme-alpine":"#508c73","theme-teal":"#009f9a","theme-violet":"#9665da","theme-copper":"#b66e38","theme-aurora":"#62c9f0"}[item.sku]||"#ff7a00"),border:item.kind==="HIGHLIGHT"?"3px solid #ff8b27":item.kind==="SUPPORTER"?"2px solid #e2bd35":"2px solid var(--preview-color)",borderRadius:18,padding:12,marginBottom:12,background:item.kind==="SUPPORTER"?"linear-gradient(145deg,#d5aa09,#927000 55%,#211900)":item.kind==="HIGHLIGHT"?"linear-gradient(145deg,#fff9ea,#ffe8cc)":"linear-gradient(135deg,#f6f9fc,var(--preview-color))",boxShadow:item.kind==="HIGHLIGHT"?"0 0 0 3px rgba(255,137,35,.13),0 12px 28px rgba(255,122,24,.2)":"0 8px 20px rgba(20,40,60,.11)",minHeight:126}}><div style={{fontSize:10,fontWeight:900,color:item.kind==="SUPPORTER"?"#fff4c1":"#39485a",marginBottom:9}}>{item.kind==="HIGHLIGHT"?"✨ HERVORGEHOBEN":item.kind==="SUPPORTER"?"⭐ SUPPORTER":"DESIGN · "+item.title}</div><div style={{display:"flex",alignItems:"center",gap:10,padding:9,borderRadius:12,background:item.kind==="SUPPORTER"?"rgba(30,22,0,.5)":"rgba(255,255,255,.94)",color:item.kind==="SUPPORTER"?"#fff":"#25374a"}}><img src={profile?.avatar_url||"/default-avatar.svg"} alt="" style={{width:50,height:50,borderRadius:"50%",objectFit:"cover",border:"2px solid "+(item.kind==="HIGHLIGHT"?"#ff9b45":item.kind==="SUPPORTER"?"#f9dc70":"var(--preview-color)")}}/><div style={{minWidth:0,flex:1}}><strong style={{display:"flex",alignItems:"center",gap:5,fontSize:13}}>{item.kind==="SUPPORTER"&&<img src="/supporter-star.svg" alt="Supporter-Stern" style={{width:24,height:24}}/>}{profile?.nickname||"Dein Profil"}</strong><small style={{display:"block",marginTop:4}}>{item.kind==="HIGHLIGHT"?"Hervorgehobenes Mitglied":item.kind==="SUPPORTER"?"Supporter · Mitgliederkarte":"Mitglied · Layoutvorschau"}</small></div></div></div>:item.image_url?<img src={item.image_url} alt={item.title} loading="lazy" style={{width:"100%",aspectRatio:"16/10",objectFit:"cover",borderRadius:12,marginBottom:10}}/>:<div style={{padding:22,background:"#eef3f7",borderRadius:12,marginBottom:12,textAlign:"center"}}>🛍️ Artikelvorschau</div>}
 <strong>{item.kind==="LAYOUT"?"🎨":item.kind==="SUPPORTER"?"⭐":item.kind==="HIGHLIGHT"?"✨":item.kind==="DECORATION"?"🎨":"👀"} {item.title}</strong><p>{item.description}</p><p><strong>{item.price} [k]</strong></p>
 <button type="button" disabled={busy||owned||Number(market?.balance??0)<item.price} onClick={()=>buy(item.sku,item.title,item.price)}>{owned?"Bereits erworben":Number(market?.balance??0)<item.price?"Nicht genug [k]":"Jetzt kaufen"}</button>
 <p><button type="button" disabled={busy} onClick={()=>wish(item.sku)}>{(market?.wishlist||[]).includes(item.sku)?"♥ Von Wunschliste entfernen":"♡ Merken"}</button></p>
 {isHead&&<div style={{display:"grid",gap:8,marginTop:12}}><button type="button" disabled={busy} onClick={()=>changePrice(item.sku,item.price)}>Preis bearbeiten</button><label style={{fontSize:12,fontWeight:700}}>Artikelfoto hochladen (max. 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void uploadImage(item.sku,e.target.files?.[0]);e.target.value="";}}/></label>{uploadingSku===item.sku&&<small>Foto wird hochgeladen …</small>}</div>}</article>})}</div></>}
 {error&&<div role="alert" style={{padding:12,border:"1px solid #e7a19c",borderRadius:12,marginTop:12}}><strong>Marktplatz konnte nicht vollständig geladen werden.</strong><p>{error}</p><button type="button" onClick={()=>void load()}>Erneut versuchen</button></div>}
 </section>;
}