import { useEffect, useMemo, useState } from "react";
import { supabase } from "./supabaseClient";
import { Search, Users, User, ShieldCheck, Crown, Star, Circle, MessageCircle, Lock, Unlock, Settings2, RefreshCw, X } from "lucide-react";

const ROLE_LABELS={MEMBER:"Mitglied",SUPPORTER:"Supporter",ADMIN:"Admin",HEAD_ADMIN:"Head Admin"};
const ROLE_ORDER={MEMBER:1,SUPPORTER:2,ADMIN:3,HEAD_ADMIN:4};
const normalizeRole=(role)=>{const v=String(role||"MEMBER").toUpperCase();if(v==="USER")return "MEMBER";if(v==="MODERATOR")return "ADMIN";if(v==="OWNER")return "HEAD_ADMIN";return ROLE_LABELS[v]?v:"MEMBER"};
const getDisplayName=(m)=>m?.nickname||[m?.first_name,m?.last_name].filter(Boolean).join(" ")||"Mitglied";
const getAge=(d)=>{if(!d)return null;const b=new Date(d),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a};
const Avatar=({member,large=false})=><img className={`members-avatar ${large?"large":""}`} src={member?.avatar_url||"/default-avatar.svg"} alt={getDisplayName(member)} onError={e=>e.currentTarget.src="/default-avatar.svg"}/>;

export default function Members({onNavigate,onOpenProfile,onMessage}){
 const [members,setMembers]=useState([]);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [currentUserId,setCurrentUserId]=useState(null);const [currentRole,setCurrentRole]=useState("MEMBER");const [selected,setSelected]=useState(null);const [saving,setSaving]=useState(false);const [blocked,setBlocked]=useState([]);const [suspended,setSuspended]=useState([]);
 const isHeadAdmin=currentRole==="HEAD_ADMIN";const isAdmin=isHeadAdmin||currentRole==="ADMIN";
 const loadData=async()=>{setLoading(true);setError("");try{const {data:{user},error:a}=await supabase.auth.getUser();if(a)throw a;setCurrentUserId(user?.id||null);if(!user){setMembers([]);return}const [{data:profiles,error:p},{data:blocks,error:b},{data:current,error:cp}]=await Promise.all([supabase.from("profiles").select("*"),supabase.from("user_blocks").select("*").eq("blocker_id",user.id),supabase.from("profiles").select("role").eq("id",user.id).maybeSingle()]);if(p)throw p;if(b)throw b;if(cp)throw cp;setCurrentRole(normalizeRole(current?.role));setBlocked(blocks||[]);setMembers((profiles||[]).filter(x=>x.account_status!=="SUSPENDED").sort((a,b)=>(ROLE_ORDER[normalizeRole(b.role)]||0)-(ROLE_ORDER[normalizeRole(a.role)]||0)||getDisplayName(a).localeCompare(getDisplayName(b),"de")));}catch(e){console.error(e);setError(e.message||"Mitglieder konnten nicht geladen werden.")}finally{setLoading(false)}};
 useEffect(()=>{loadData()},[]);
 const blockedIds=useMemo(()=>new Set(blocked.map(x=>x.blocked_id)),[blocked]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return members.filter(m=>m.id!==currentUserId&&!blockedIds.has(m.id)&&[m.nickname,m.first_name,m.last_name,m.role].filter(Boolean).join(" ").toLowerCase().includes(q))},[members,search,currentUserId,blockedIds]);
 async function toggleSuspend(member){if(!isAdmin||member.role==="HEAD_ADMIN")return;setSaving(true);try{if(member.account_status==="SUSPENDED"){const {error}=await supabase.rpc("admin_set_account_status",{target_user:member.id,new_status:"ACTIVE",reason_text:null});if(error)throw error}else{const reason=window.prompt(`Grund für die Sperre von ${getDisplayName(member)}:`);if(!reason||reason.trim().length<5){alert("Bitte einen konkreten Sperrgrund angeben.");return}const {error}=await supabase.rpc("admin_set_account_status",{target_user:member.id,new_status:"SUSPENDED",reason_text:reason.trim()});if(error)throw error}await loadData()}catch(e){alert(e.message||"Aktion fehlgeschlagen.")}finally{setSaving(false)}}
 async function blockMember(member){const {error}=await supabase.from("user_blocks").insert({blocker_id:currentUserId,blocked_id:member.id});if(error)return alert(error.message);setSelected(null);await loadData()}
 async function unblockMember(member){const {error}=await supabase.from("user_blocks").delete().eq("blocker_id",currentUserId).eq("blocked_id",member.id);if(error)return alert(error.message);await loadData()}
 const open=(m)=>{setSelected(null);if(onOpenProfile)onOpenProfile(m);else onNavigate?.("member-profile",m)};
 if(loading)return <div className="members-page"><div className="members-loading">Mitglieder werden geladen...</div></div>;
 return <div className="members-page">
  <section className="members-header"><div><div className="members-kicker"><Users size={16}/> COMMUNITY</div><h1>Mitglieder</h1><p>Entdecke die Community und verwalte Mitglieder.</p></div><div className="members-header-count"><Users size={18}/><div><strong>{members.length}</strong><span>Mitglieder</span></div></div></section>
  {error&&<div className="members-error"><span>{error}</span><button onClick={loadData}><RefreshCw size={16}/> Erneut versuchen</button></div>}
  <div className="members-toolbar"><div className="members-search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Mitglieder suchen..."/>{search&&<button onClick={()=>setSearch("")}><X size={17}/></button>}</div><button className="members-refresh" onClick={loadData}><RefreshCw size={16}/> Aktualisieren</button></div>
  <section className="members-section"><div className="section-heading"><div><h2>Community-Mitglieder</h2><p>{filtered.length} sichtbar</p></div></div><div className="members-grid">
   {filtered.map(member=>{const role=normalizeRole(member.role);return <article key={member.id} className={`member-card role-${role.toLowerCase()}`} onClick={()=>open(member)}>
    <div className="member-card-top"><div className="member-status-avatar"><Avatar member={member}/><span className={`status-dot ${member.is_online?"online":"offline"}`}/></div><div className="member-role">{role==="HEAD_ADMIN"?<Crown size={15}/>:role==="ADMIN"?<ShieldCheck size={15}/>:role==="SUPPORTER"?<Star size={15}/>:<User size={15}/>} {ROLE_LABELS[role]}</div></div>
    <div className="member-info"><h3>{getDisplayName(member)}</h3><div className="member-online-status"><Circle size={8} fill="currentColor"/>{member.is_online?"Online":"Offline"}</div>{member.bio&&<p className="member-bio">{member.bio}</p>}</div>
    <div className="member-actions"><button className="member-message-button" onClick={e=>{e.stopPropagation();onMessage?onMessage(member):onNavigate?.("messages",member)}}><MessageCircle size={17}/> Nachricht</button>{member.id!==currentUserId&&<button className="member-manage-button" onClick={e=>{e.stopPropagation();setSelected(member)}}><Settings2 size={16}/> Verwalten</button>}</div>
   </article>})}
  </div>{!filtered.length&&<div className="members-empty"><Users size={38}/><h3>Keine Mitglieder gefunden</h3></div>}</section>
  {selected&&<div className="member-modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="member-modal" onMouseDown={e=>e.stopPropagation()}><button className="member-modal-close" onClick={()=>setSelected(null)}><X size={21}/></button><div className="member-modal-profile"><Avatar member={selected} large/><h2>{getDisplayName(selected)}</h2><div className={`member-role role-${normalizeRole(selected.role).toLowerCase()}`}>{ROLE_LABELS[normalizeRole(selected.role)]}</div><p>{selected.bio||"Keine Beschreibung hinterlegt."}</p></div>{isAdmin&&selected.role!=="HEAD_ADMIN"&&<div className="member-admin-tools"><div className="admin-tools-label">MODERATION</div><h3>Mitglied verwalten</h3><div className="role-action-grid"><button onClick={()=>toggleSuspend(selected)} disabled={saving}>{selected.account_status==="SUSPENDED"?<><Unlock size={18}/> Freischalten</>:<><Lock size={18}/> Sperren</>}</button>{isHeadAdmin&&<button onClick={async()=>{const {error}=await supabase.rpc("admin_set_role",{target_user:selected.id,new_role:"SUPPORTER"});if(error)alert(error.message);else await loadData()}}><Star size={18}/> Supporter</button>}{isHeadAdmin&&<button onClick={async()=>{const {error}=await supabase.rpc("admin_set_role",{target_user:selected.id,new_role:"ADMIN"});if(error)alert(error.message);else await loadData()}}><ShieldCheck size={18}/> Admin</button>}<button onClick={()=>blockMember(selected)}>🚫 Blockieren</button></div></div>}<div className="modal-actions"><button className="primary-button" onClick={()=>open(selected)}>Profil öffnen</button><button className="secondary-button" onClick={()=>blockMember(selected)}>Blockieren</button></div></div></div>}
 </div>}
