import { supabase } from "./supabaseClient";
let uid=null,mounted=false,channel=null;
const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined)n.textContent=x;return n;},fmt=v=>new Date(v).toLocaleString("de-AT");
const icon=t=>t==="MESSAGE"?"💬":t==="FRIEND_REQUEST"?"👥":t==="FORUM_REPLY"?"💭":"🔔";
const navTo=t=>{const q=t==="MESSAGE"?"nachrichten":t==="FRIEND_REQUEST"?"freund":"forum";[...document.querySelectorAll(".modern-nav button,nav button,nav a")].find(n=>(n.textContent||"").toLowerCase().includes(q))?.click();};
async function prefs(){const {data}=await supabase.rpc("member_notification_settings");return data?.[0]||{notify_message_popup:true,notify_friend_request_popup:true,notify_forum_reply_popup:true};}
async function popup(n){const p=await prefs(),allowed=n.type==="MESSAGE"?p.notify_message_popup:n.type==="FRIEND_REQUEST"?p.notify_friend_request_popup:n.type==="FORUM_REPLY"?p.notify_forum_reply_popup:false;if(!allowed)return;let host=document.querySelector(".ec-toast-host");if(!host){host=el("div","ec-toast-host");document.body.append(host)}const existing=host.querySelector(`[data-type="${n.type}"]`);if(existing){const c=Number(existing.dataset.count||1)+1;existing.dataset.count=c;existing.querySelector("strong").textContent=`${c} neue ${n.type==="FORUM_REPLY"?"Antworten":n.type==="MESSAGE"?"Nachrichten":"Freundschaftsanfragen"}`;return}const t=el("button","ec-live-toast");t.dataset.type=n.type;t.dataset.count="1";t.innerHTML=`<span class="ec-toast-icon">${icon(n.type)}</span><span><strong></strong><small></small></span><span class="ec-toast-x">×</span>`;t.querySelector("strong").textContent=n.title;t.querySelector("small").textContent=n.body;t.onclick=async e=>{t.remove();if(e.target.closest(".ec-toast-x"))return;await supabase.rpc("member_mark_notification_read",{p_notification_id:n.id});navTo(n.type);refreshBadge();};host.prepend(t);setTimeout(()=>t.remove(),9000);}
async function refreshBadge(){const {count}=await supabase.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",uid).is("read_at",null);const b=document.querySelector(".ec-notification-count");if(b){b.textContent=count>99?"99+":String(count||0);b.hidden=!count}}
async function openCenter(){document.querySelector(".ec-notification-panel")?.remove();const p=el("div","ec-notification-panel"),head=el("div","ec-notification-head");head.append(el("strong",null,"Benachrichtigungen"));const all=el("button",null,"Alle gelesen");all.onclick=async()=>{await supabase.rpc("member_mark_all_notifications_read");renderList(p);refreshBadge()};head.append(all);p.append(head);const settings=document.createElement("details");settings.className="ec-notification-settings";settings.innerHTML="<summary>⚙ Popup-Einstellungen</summary><div></div>";const box=settings.lastElementChild,pr=await prefs();[["Private Nachrichten","notify_message_popup"],["Freundschaftsanfragen","notify_friend_request_popup"],["Antworten auf meine Forenbeiträge","notify_forum_reply_popup"]].forEach(([label,key])=>{const l=el("label"),c=el("input");c.type="checkbox";c.checked=!!pr[key];l.append(c,document.createTextNode(label));box.append(l)});const save=el("button","primary-button","Speichern");save.onclick=async()=>{const c=[...box.querySelectorAll("input")];const {error}=await supabase.rpc("member_update_notification_settings",{p_message:c[0].checked,p_friend:c[1].checked,p_forum:c[2].checked});if(error)alert(error.message);else settings.open=false};box.append(save);p.append(settings,el("div","ec-notification-list"));document.body.append(p);await renderList(p);}
async function renderList(p){const list=p.querySelector(".ec-notification-list");list.textContent="Lade …";const {data,error}=await supabase.from("notifications").select("id,title,body,type,read_at,created_at").eq("user_id",uid).order("created_at",{ascending:false}).limit(40);list.replaceChildren();if(error){list.textContent="Benachrichtigungen konnten nicht geladen werden. Bitte später erneut versuchen.";return}if(!data?.length){list.append(el("p","ec-notification-empty","Alles ruhig – noch keine Benachrichtigungen."));return}const groups=[];for(const n of data){const prev=groups.at(-1);if(prev&&prev.type===n.type&&!prev.read_at&&!n.read_at&&new Date(prev.created_at)-new Date(n.created_at)<3600000)prev.items.push(n);else groups.push({...n,items:[n]})}groups.forEach(g=>{const r=el("button",`ec-notification-row${g.read_at?"":" unread"}`);r.append(el("span","ec-notification-icon",icon(g.type)));const txt=el("span"),many=g.items.length>1;txt.append(el("strong",null,many?`${g.items.length} neue ${g.type==="FORUM_REPLY"?"Antworten":g.type==="MESSAGE"?"Nachrichten":"Freundschaftsanfragen"}`:g.title),el("small",null,many?"Mehrere neue Hinweise wurden zusammengefasst.":g.body),el("time",null,fmt(g.created_at)));r.append(txt);r.onclick=async()=>{for(const n of g.items)await supabase.rpc("member_mark_notification_read",{p_notification_id:n.id});navTo(g.type);p.remove();refreshBadge()};list.append(r)})}
async function mount(){if(mounted)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;uid=user.id;const nav=document.querySelector(".modern-nav,nav");if(!nav)return;const wrap=el("div","ec-notification-bell-wrap"),btn=el("button","ec-notification-bell","🔔 Benachrichtigungen"),count=el("span","ec-notification-count","0");count.hidden=true;btn.type="button";btn.title="Benachrichtigungen";btn.onclick=e=>{e.stopPropagation();document.querySelector(".ec-notification-panel")?document.querySelector(".ec-notification-panel").remove():openCenter()};wrap.append(btn,count);nav.append(wrap);mounted=true;await refreshBadge();channel=supabase.channel(`ec-notification-center-${uid}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications",filter:`user_id=eq.${uid}`},payload=>{refreshBadge();popup(payload.new)}).subscribe();document.addEventListener("click",e=>{const p=document.querySelector(".ec-notification-panel");if(p&&!p.contains(e.target)&&!wrap.contains(e.target))p.remove()});obs.disconnect();}
window.addEventListener("ec:open-notifications",()=>{void mount().then(()=>{if(uid)void openCenter();});});
let timer;const obs=new MutationObserver(()=>{if(mounted)return;clearTimeout(timer);timer=setTimeout(mount,250)});obs.observe(document.documentElement,{childList:true,subtree:true});void mount();window.addEventListener("beforeunload",()=>{if(channel)supabase.removeChannel(channel)});