import { supabase } from './supabaseClient';

const TOP_LINKS=[['⌂','Startseite','home'],['♟','Mitglieder','members'],['▤','Forum','forum'],['●','Gruppen','groups'],['▣','Events','events'],['▦','Neuigkeiten','news'],['▥','Betriebe','ads']];
const DOCK_LINKS=[['●','Mein Profil','profile'],['✉','Nachrichten','messages'],['♥','Freunde','friends'],['◇','Anfragen','requests'],['⊘','Blockiert','blocked'],['⚙','Einstellungen','profile'],['?','Hilfe','help']];
const FALLBACK_REGIONS=[{slug:'ennstal',name:'Ennstal'},{slug:'leoben-bruck-muerzzuschlag',name:'Leoben – Bruck – Mürzzuschlag'},{slug:'salzkammergut',name:'Salzkammergut'}];
let regions=FALLBACK_REGIONS;let activeRegion=null;let regionalAssignments=[];let currentProfile=null;
const clickPage=(page)=>{const selectors=[`[data-page="${page}"]`,`[data-nav="${page}"]`,`button[data-page="${page}"]`];for(const s of selectors){const el=document.querySelector(s);if(el){el.click();return true}}const wanted={home:'Startseite',members:'Mitglieder',forum:'Forum',groups:'Gruppen',events:'Events',news:'Neuigkeiten',ads:'Betriebe',profile:'Mein Profil',messages:'Nachrichten',friends:'Freunde',requests:'Anfragen',blocked:'Blockiert',help:'Hilfe'}[page];if(wanted){const all=[...document.querySelectorAll('button,a')];const el=all.find(x=>x.textContent?.trim().includes(wanted)&&!x.closest('.ec-regional-shell'));if(el){el.click();return true}}return false};
const effectiveRole=(card)=>{const base=(card.dataset.baseRole||'MEMBER').toUpperCase();if(base==='HEAD_ADMIN')return'HEAD_ADMIN';if(base==='ADMIN')return'ADMIN';const memberId=card.dataset.memberId;if(activeRegion&&regionalAssignments.some(a=>a.user_id===memberId&&a.region_id===activeRegion.id&&a.active))return'ADMIN';if(base==='SUPPORTER'||regionalAssignments.some(a=>a.user_id===memberId&&a.active))return'SUPPORTER';return'MEMBER'};
function applyRegionalDirectory(){if(!activeRegion)return;document.documentElement.dataset.ecRegion=activeRegion.slug;document.querySelectorAll('.member-card[data-member-id]').forEach(card=>{const role=effectiveRole(card);const home=card.dataset.homeRegionId;const visible=role==='HEAD_ADMIN'||role==='ADMIN'||!home||home===activeRegion.id;card.hidden=!visible;card.dataset.effectiveRole=role;card.classList.toggle('ec-regional-admin',role==='ADMIN'&&(card.dataset.baseRole||'').toUpperCase()!=='ADMIN');});document.querySelectorAll('.ec-region-context').forEach(x=>x.remove());const grid=document.querySelector('.member-grid');if(grid){const label=document.createElement('div');label.className='ec-region-context';label.textContent=`Region: ${activeRegion.name}`;grid.before(label)}}
async function loadRegionalContext(){try{const [{data:rs},{data:assignments},{data:{user}}]=await Promise.all([supabase.from('regions').select('id,slug,name,short_name,sort_order').eq('is_active',true).order('sort_order'),supabase.from('regional_admin_assignments').select('user_id,region_id,active').eq('active',true),supabase.auth.getUser()]);if(rs?.length)regions=rs;regionalAssignments=assignments||[];if(user){const {data:p}=await supabase.from('profiles').select('id,role,home_region_id').eq('id',user.id).maybeSingle();currentProfile=p||null}const saved=localStorage.getItem('ec-active-region');activeRegion=regions.find(r=>r.slug===saved)||regions.find(r=>r.id===currentProfile?.home_region_id)||regions[0];if(activeRegion)localStorage.setItem('ec-active-region',activeRegion.slug);renderRegionOptions();applyRegionalDirectory()}catch(error){console.warn('Regionen konnten nicht vollständig geladen werden:',error)}}
function renderRegionOptions(){const picker=document.querySelector('.ec-region-picker select');if(!picker)return;picker.innerHTML=regions.map(r=>`<option value="${r.slug}">${r.name}</option>`).join('');picker.value=activeRegion?.slug||regions[0]?.slug||'ennstal'}
function ensureShell(){if(!document.querySelector('.modern-main')||document.querySelector('.ec-regional-shell')){applyRegionalDirectory();return}const shell=document.createElement('div');shell.className='ec-regional-shell';shell.innerHTML=`<nav class="ec-top-nav" aria-label="Hauptnavigation">${TOP_LINKS.map(([i,l,p])=>`<button type="button" data-ec-page="${p}"><b>${i}</b><span>${l}</span></button>`).join('')}<label class="ec-region-picker"><b>⌖</b><select aria-label="Region"></select></label><button class="ec-dock-toggle" type="button" aria-label="Menü öffnen">☰</button></nav><aside class="ec-right-dock" aria-label="Persönliche Funktionen"><button class="ec-dock-close" type="button" aria-label="Menü schließen">×</button>${DOCK_LINKS.map(([i,l,p])=>`<button type="button" data-ec-page="${p}" title="${l}" aria-label="${l}"><b>${i}</b><span>${l}</span></button>`).join('')}<button type="button" class="ec-logout" title="Abmelden" aria-label="Abmelden"><b>↪</b><span>Abmelden</span></button></aside>`;document.body.appendChild(shell);shell.querySelectorAll('[data-ec-page]').forEach(b=>b.onclick=()=>{clickPage(b.dataset.ecPage);document.body.classList.remove('ec-dock-open');setTimeout(applyRegionalDirectory,50)});shell.querySelector('.ec-dock-toggle').onclick=()=>document.body.classList.add('ec-dock-open');shell.querySelector('.ec-dock-close').onclick=()=>document.body.classList.remove('ec-dock-open');shell.querySelector('.ec-logout').onclick=()=>{const el=[...document.querySelectorAll('button')].find(x=>x.textContent?.trim().includes('Abmelden')&&!x.closest('.ec-regional-shell'));el?.click()};shell.querySelector('select').onchange=e=>{const next=regions.find(r=>r.slug===e.target.value);if(!next)return;activeRegion=next;localStorage.setItem('ec-active-region',next.slug);window.dispatchEvent(new CustomEvent('ec:region-change',{detail:next}));applyRegionalDirectory()};document.body.classList.add('ec-regional-ui');renderRegionOptions();applyRegionalDirectory()}
let queued=false;const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;ensureShell()})});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('DOMContentLoaded',()=>{ensureShell();loadRegionalContext()});ensureShell();loadRegionalContext();