import { supabase } from './supabaseClient';

let viewer=null,profiles=[],regions=[],regionalAdmins=[],booting=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const regionName=id=>regions.find(r=>r.id===id)?.name||'Nicht festgelegt';
const isHead=()=>String(viewer?.role||'').toUpperCase()==='HEAD_ADMIN';
const fmtDate=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('de-AT')};
const age=v=>{if(!v)return'';const b=new Date(v),n=new Date();if(Number.isNaN(b.getTime()))return'';let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return `${a} Jahre`};

async function loadContext(force=false){
  if(!force&&viewer&&profiles.length&&regions.length)return;
  const [{data:{user}},{data:ps},{data:rs},{data:ra}]=await Promise.all([
    supabase.auth.getUser(),
    supabase.from('profiles').select('*').eq('account_status','ACTIVE').order('nickname'),
    supabase.from('regions').select('id,slug,name,sort_order').eq('is_active',true).order('sort_order'),
    supabase.from('regional_admin_assignments').select('user_id,region_id,active').eq('active',true)
  ]);
  profiles=ps||[];regions=rs||[];regionalAdmins=ra||[];viewer=profiles.find(p=>p.id===user?.id)||null;
}

function activeRegion(){const s=document.querySelector('.ec-region-picker select')?.value||localStorage.getItem('ec-active-region');return regions.find(r=>r.slug===s)||regions.find(r=>r.id===viewer?.home_region_id)||regions[0]||null}

function ensureBranding(){
  const standard='/ennstal-connect-community-logo.png';
  document.querySelectorAll('img').forEach(img=>{const src=String(img.getAttribute('src')||'');if(/ennstal-connect-(brand-2026|logo-v2|community-logo|logo-neon)\.(png|svg)$/i.test(src.replace(/^\//,'')))img.src=standard});
  const brand=document.querySelector('.ec-brand-logo');if(brand)brand.innerHTML=`<img class="ec-standard-logo" src="${standard}" alt="Ennstal Connect">`;
}

function memberFunction(m){const role=String(m.role||'MEMBER').toUpperCase();const assigned=regionalAdmins.filter(a=>a.user_id===m.id&&a.active).map(a=>regionName(a.region_id));if(role==='HEAD_ADMIN')return'★ Hauptadmin';if(role==='ADMIN')return'★ Global Admin';if(assigned.length)return`★ Regional Admin ${assigned.join(', ')}`;if(role==='SUPPORTER')return'★ Supporter';return`Mitglied · ${regionName(m.home_region_id)}`}
function row(label,value){if(value===undefined||value===null||String(value).trim()==='')return'';return`<div class="ec-stable-row"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function memberFromProfilePage(root){const title=(root.querySelector('.member-profile-hero h1,.ec-stable-name')?.textContent||'').trim();return profiles.find(p=>p.nickname===title)||profiles.find(p=>[p.first_name,p.last_name].filter(Boolean).join(' ')===title)||null}
async function areFriends(member){if(!viewer?.id||viewer.id===member.id)return false;const{data}=await supabase.from('friendships').select('id').eq('status','ACCEPTED').or(`and(requester_id.eq.${viewer.id},receiver_id.eq.${member.id}),and(requester_id.eq.${member.id},receiver_id.eq.${viewer.id})`).limit(1);return Boolean(data?.length)}
function privacyAllows(m,f,isFriend){if(viewer?.id===m.id||['HEAD_ADMIN','ADMIN'].includes(String(viewer?.role||'').toUpperCase()))return true;const s=String(m?.privacy_settings?.[f]||'PUBLIC').toUpperCase();return s==='PUBLIC'||(s==='FRIENDS'&&isFriend)}

function closeModal(){document.querySelector('.ec-admin-direct-modal')?.remove();document.querySelector('.ec-stable-admin-modal')?.remove()}
async function saveMemberAction(member,action,slug,status){
  if(action==='home'){const{error}=await supabase.rpc('ec_head_set_home_region',{p_target:member.id,p_region_slug:slug});if(error)throw error}
  if(action==='regional-on'||action==='regional-off'){const{error}=await supabase.rpc('ec_set_regional_admin',{p_target:member.id,p_region_slug:slug,p_enabled:action==='regional-on'});if(error)throw error}
  if(action==='global-on'||action==='global-off'){const{error}=await supabase.rpc('ec_set_global_admin',{p_target:member.id,p_enabled:action==='global-on'});if(error)throw error}
  if(action==='demote'){const{error}=await supabase.rpc('ec_demote_global_to_regional_admin',{p_target:member.id,p_region_slug:slug});if(error)throw error}
  status.textContent='Gespeichert.';status.className='ec-admin-direct-status success';await loadContext(true);
}

async function openMemberAdmin(member){
  if(!isHead())return;closeModal();const assigned=regionalAdmins.filter(a=>a.user_id===member.id&&a.active);const modal=document.createElement('div');modal.className='ec-stable-admin-modal';
  modal.innerHTML=`<div class="ec-stable-admin-dialog"><div class="ec-stable-admin-head"><div><span>HEAD ADMIN</span><h2>${esc(member.nickname||'Mitglied')} verwalten</h2><p>Heimatregion, Global- und Regionalrechte</p></div><button class="ec-stable-admin-close">×</button></div><div class="ec-stable-admin-summary"><b>Rolle</b><span>${esc(memberFunction(member))}</span><b>Heimatregion</b><span>${esc(regionName(member.home_region_id))}</span><b>Regional Admin</b><span>${assigned.length?assigned.map(a=>esc(regionName(a.region_id))).join(', '):'Keine'}</span></div><div class="ec-stable-admin-form"><label>Heimatregion<select class="ec-home">${regions.map(r=>`<option value="${r.slug}" ${r.id===member.home_region_id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><button data-a="home">Heimatregion speichern</button><label>Region für Adminrechte<select class="ec-region"><option value="">Region wählen</option>${regions.map(r=>`<option value="${r.slug}">${esc(r.name)}</option>`).join('')}</select></label><div class="ec-stable-admin-buttons"><button data-a="regional-on">Regional Admin vergeben</button><button data-a="regional-off">Regional Admin entfernen</button></div>${String(member.role).toUpperCase()==='ADMIN'?'<button data-a="demote">Global Admin → Regional Admin</button>':'<button data-a="global-on">Global Admin vergeben</button>'}${String(member.role).toUpperCase()==='ADMIN'?'<button data-a="global-off">Global Admin entfernen</button>':''}</div><div class="ec-admin-direct-status"></div></div>`;
  document.body.appendChild(modal);modal.querySelector('.ec-stable-admin-close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
  const status=modal.querySelector('.ec-admin-direct-status');modal.querySelector('.ec-stable-admin-form').onclick=async e=>{const action=e.target?.dataset?.a;if(!action)return;const slug=(action==='home'?modal.querySelector('.ec-home'):modal.querySelector('.ec-region')).value;if(!['global-on','global-off'].includes(action)&&!slug){status.textContent='Bitte Region auswählen.';return}e.target.disabled=true;status.textContent='Wird gespeichert …';try{await saveMemberAction(member,action,slug,status);setTimeout(()=>openMemberAdmin(profiles.find(p=>p.id===member.id)||member),300)}catch(err){status.textContent=err.message||'Speichern fehlgeschlagen';status.className='ec-admin-direct-status error'}finally{e.target.disabled=false}};
}

async function openAdminCenter(regionsOnly=false){
  if(!isHead())return;await loadContext(true);closeModal();const modal=document.createElement('div');modal.className='ec-admin-direct-modal';
  modal.innerHTML=`<div class="ec-admin-direct-box"><div class="ec-admin-direct-head"><div><span>HEAD ADMIN</span><h2>${regionsOnly?'Regionen & Rechte':'Admin-Zentrale'}</h2><p>Mitglieder, Heimatregionen und Rollen direkt verwalten.</p></div><button class="ec-admin-direct-close">×</button></div><div class="ec-admin-direct-toolbar"><input type="search" placeholder="Mitglied suchen …"><select><option value="">Alle Regionen</option>${regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></div><div class="ec-admin-direct-list"></div></div>`;document.body.appendChild(modal);
  modal.querySelector('.ec-admin-direct-close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};const input=modal.querySelector('input'),filter=modal.querySelector('select'),list=modal.querySelector('.ec-admin-direct-list');
  const render=()=>{const q=input.value.trim().toLowerCase(),rid=filter.value;const items=profiles.filter(p=>p.id!==viewer.id).filter(p=>(!rid||p.home_region_id===rid)&&(!q||`${p.nickname||''} ${p.first_name||''} ${p.last_name||''}`.toLowerCase().includes(q)));list.innerHTML=items.map(p=>`<article data-id="${p.id}"><div><strong>${esc(p.nickname||[p.first_name,p.last_name].filter(Boolean).join(' ')||'Mitglied')}</strong><small>${esc(memberFunction(p))} · ${esc(regionName(p.home_region_id))}</small></div><button type="button">Verwalten</button></article>`).join('')||'<p>Keine Mitglieder gefunden.</p>';list.querySelectorAll('article button').forEach(b=>b.onclick=()=>openMemberAdmin(profiles.find(p=>p.id===b.closest('article').dataset.id)))};input.oninput=render;filter.onchange=render;render();
}

async function enhanceMemberProfile(root){
  if(root.dataset.ecStableProfile==='1')return;const hero=root.querySelector(':scope > .member-profile-hero');if(!hero)return;const member=memberFromProfilePage(root);if(!member)return;root.dataset.ecStableProfile='1';root.classList.add('ec-stable-profile-page');const friend=await areFriends(member),avatar=hero.querySelector('img'),sourceActions=root.querySelector(':scope > .member-profile-actions'),sourceAdmin=root.querySelector(':scope > .member-admin-tools');
  const layout=document.createElement('section');layout.className='ec-stable-profile-card';const left=document.createElement('div');left.className='ec-stable-profile-left';const photo=document.createElement('div');photo.className='ec-stable-photo';if(avatar)photo.appendChild(avatar);left.appendChild(photo);const role=document.createElement('div');role.className='ec-stable-role';role.innerHTML=`<span>Funktion</span><strong>${esc(memberFunction(member))}</strong><small>Heimatregion: ${esc(regionName(member.home_region_id))}</small>`;left.appendChild(role);const actions=document.createElement('div');actions.className='ec-stable-actions';if(sourceActions){[...sourceActions.querySelectorAll('button')].forEach(btn=>{btn.classList.add('ec-stable-action');btn.textContent=(btn.textContent||'').replace(/[💬🤝♥✓⏳🚫🚩]/g,'').replace(/\s+/g,' ').trim();actions.appendChild(btn)});sourceActions.hidden=true}left.appendChild(actions);if(isHead()){const admin=document.createElement('button');admin.type='button';admin.className='ec-stable-admin-toggle';admin.textContent='Admin Tools';admin.onclick=()=>openMemberAdmin(member);left.appendChild(admin)}
  const data=document.createElement('div');data.className='ec-stable-profile-data';const rows=[row('Nickname',member.nickname)];if(privacyAllows(member,'name',friend)){rows.push(row('Vorname',member.first_name),row('Nachname',member.last_name))}if(privacyAllows(member,'birth_date',friend)){rows.push(row('Geburtsdatum',fmtDate(member.birth_date)),row('Alter',age(member.birth_date)))}if(privacyAllows(member,'location',friend))rows.push(row('Wohnort',member.location));rows.push(row('Heimatregion',regionName(member.home_region_id)));data.innerHTML=`<div class="ec-stable-data-head"><div><span>MITGLIEDSPROFIL</span><h1 class="ec-stable-name">${esc(member.nickname||'Mitglied')}</h1></div>${member.is_verified?'<b title="Verifiziert">✓</b>':''}</div><div class="ec-stable-data-grid">${rows.join('')}</div>`;layout.append(left,data);root.insertBefore(layout,hero);hero.hidden=true;if(sourceAdmin)sourceAdmin.hidden=true;
  const more=document.createElement('div');more.className='ec-stable-more';if(member.bio&&privacyAllows(member,'bio',friend)){const about=document.createElement('section');about.className='ec-stable-section';about.innerHTML=`<span>ÜBER MICH</span><h2>Über ${esc(member.nickname||'dieses Mitglied')}</h2><p>${esc(member.bio)}</p>`;more.appendChild(about)}const details=[];if(privacyAllows(member,'interests',friend)&&member.interests)details.push(row('Interessen',Array.isArray(member.interests)?member.interests.join(', '):member.interests));if(privacyAllows(member,'website',friend)&&member.website)details.push(row('Webseite',member.website));if(details.length){const info=document.createElement('section');info.className='ec-stable-section';info.innerHTML=`<span>WEITERE ANGABEN</span><h2>Profilinformationen</h2><div class="ec-stable-data-grid one">${details.join('')}</div>`;more.appendChild(info)}if(more.children.length)layout.after(more);
}

function allRegionsMode(r){return Boolean(document.querySelector('.ec-all-regions-toggle')?.textContent?.includes(`Nur ${r.name}`))}
function filterMemberDirectory(){const r=activeRegion();if(!r)return;const all=allRegionsMode(r);document.querySelectorAll('.member-grid .member-card').forEach(card=>{const name=(card.querySelector('.member-nickname')?.textContent||card.querySelector('strong')?.textContent||'').trim();const p=profiles.find(x=>x.nickname===name)||profiles.find(x=>[x.first_name,x.last_name].filter(Boolean).join(' ')===name);if(!p)return;card.dataset.memberId=p.id;card.dataset.homeRegionId=p.home_region_id||'';card.hidden=all?false:p.home_region_id!==r.id});ensureMembersToolbar()}
function ensureMembersToolbar(){const grid=document.querySelector('.member-grid');if(!grid)return;let bar=document.querySelector('.ec-stable-member-toolbar');if(!bar){bar=document.createElement('div');bar.className='ec-stable-member-toolbar';grid.before(bar)}const r=activeRegion(),nativeSearch=[...document.querySelectorAll('input')].find(i=>/mitglied/i.test(i.placeholder||''));if(nativeSearch)nativeSearch.classList.add('ec-native-member-search');bar.innerHTML=`<label><span>Suche</span><input type="search" placeholder="Mitglied suchen …" value="${esc(nativeSearch?.value||'')}"></label><label><span>Region</span><select>${regions.map(x=>`<option value="${x.slug}" ${x.id===r?.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><button type="button">${allRegionsMode(r)?`Nur ${esc(r?.name||'Region')}`:'Alle Regionen'}</button>`;bar.querySelector('input').oninput=e=>{if(!nativeSearch)return;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;setter?.call(nativeSearch,e.target.value);nativeSearch.dispatchEvent(new Event('input',{bubbles:true}));nativeSearch.dispatchEvent(new Event('change',{bubbles:true}))};bar.querySelector('select').onchange=e=>{const native=document.querySelector('.ec-region-picker select');if(native){native.value=e.target.value;native.dispatchEvent(new Event('change',{bubbles:true}))}};bar.querySelector('button').onclick=()=>document.querySelector('.ec-all-regions-toggle')?.click()}

function ensureAdminDock(){const dock=document.querySelector('.ec-right-dock');if(!dock)return;dock.querySelectorAll('.ec-dock-admin-slot,.ec-dock-admin-recovery').forEach(el=>el.hidden=true);if(!isHead())return;let box=dock.querySelector('.ec-stable-admin-dock');if(!box){box=document.createElement('div');box.className='ec-stable-admin-dock';box.innerHTML='<div class="ec-dock-divider"></div><div class="ec-dock-section-label">VERWALTUNG</div><button data-a="center"><b>⚙</b><span>Admin-Zentrale</span></button><button data-a="regions"><b>⌖</b><span>Regionen & Rechte</span></button>';const community=[...dock.querySelectorAll('.ec-dock-section-label')].find(x=>/COMMUNITY/i.test(x.textContent||''));dock.insertBefore(box,community?.previousElementSibling||community||dock.querySelector('.ec-logout'));box.querySelector('[data-a="center"]').onclick=()=>openAdminCenter(false);box.querySelector('[data-a="regions"]').onclick=()=>openAdminCenter(true)}}

async function run(){if(booting)return;booting=true;try{await loadContext();ensureBranding();ensureAdminDock();filterMemberDirectory();document.querySelectorAll('.member-profile-page:not(.public-profile-preview)').forEach(enhanceMemberProfile)}finally{booting=false}}
new MutationObserver(()=>requestAnimationFrame(run)).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('ec:region-change',()=>setTimeout(filterMemberDirectory,30));window.addEventListener('DOMContentLoaded',run);run();